config/routes.rb
SampleApp2::Application.routes.draw do

  root             'static_pages#home'

  get 'help'    => 'static_pages#help'

  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def hello
    render text: "heloo!world"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://ruby.com/"> Ruby exercise</a>
    by me
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",    about_path %></li>
      <li><%= link_to "Contact",  contact_path %></li>
      <li><a href="http://news.ruby.com/"> News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-trubolinks-track" => true %>
    <%= javascript_include_tag "application", "data-trubolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>
<h1>About Us</h1>
<p>
    Get help on the Ruby on rails tutotrail at the
    <a href="http:ruby.com"> Ruby help page</a>
    to see help regarding this ask me ;)
    <a href="http:ruby.com"> Ruby help page</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
    Get help on the Ruby on rails tutotrail at the
    <a href="http//:ruby.com/contact"> contact page</a>
    to see help regarding this ask me ;)
    <a href="http:ruby.com"> Ruby help page</a>
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href="http://ruby.com"> Ruby help page</a>
    to see help regarding this ask me ;)
    <a href="http:ruby.com"> Ruby help page</a>
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary"%>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>this will be a signup page for new users.</p>